(function(){
'use strict';
const REV='c68110c495a895be77e349ae85fe36939974d7bc';
const RAW=`https://raw.githubusercontent.com/HiiragiNemu/magi-reader/${REV}/`;
const R2='https://pub-70a248f1a6fe4ca597e7a10f8b95dfd8.r2.dev';
const INDEX='website/public/story_index.json';
const POS=[120,850,1580];
const coll=new Intl.Collator(['zh-CN','ja-JP'],{numeric:true,sensitivity:'base'});
const S={all:[],shown:[],page:0,size:60,selected:null,player:null,oldQuest:null,oldMain:null};
const id=x=>document.getElementById(x), enc=x=>String(x).split('/').map(encodeURIComponent).join('/');
const title=e=>`${e.id} · ${(e.title||e.folder).trim()}`;
const norm=x=>String(x||'').normalize('NFKC').toLocaleLowerCase('zh-CN').replace(/\s+/g,'');
function source(e,sec,lang){let p=e.source_identity,parent=p.split('/').slice(0,-1).join('/');const i=sec.search(/\s+Section(?:\s|$)/i),stem=(i>=0?sec.slice(0,i):sec).trim().replace(/\.json$/i,'');const tree=lang==='cn'?'magireco-translate-data-master/Scenarios_full':'magireco-source-master/Scenarios_full';return `${tree}/${parent}/${stem}.json`;}
async function json(url,max){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);const b=await r.arrayBuffer();if(b.byteLength>max)throw Error('文件过大');return JSON.parse(new TextDecoder().decode(b));}
function status(t,bad){const n=id('full-story-status');if(n){n.textContent=t;n.classList.toggle('bad',!!bad);}}
async function loadIndex(){if(S.all.length)return;status('正在读取全剧情目录…');const a=await json(RAW+enc(INDEX),32*1024*1024);S.all=a.filter(e=>e&&e.game!=='exedra'&&Array.isArray(e.sections)&&e.sections.length&&e.source_identity);const c=id('full-story-category');[...new Set(S.all.map(e=>e.category))].sort(coll.compare).forEach(x=>c.append(new Option(x,x)));render();status(`目录就绪：${S.all.length.toLocaleString()} 部剧情`);}
async function loadSection(e,sec){const langs=e.has_cn&&id('full-story-cn').checked?['cn','jp']:['jp','cn'],errs=[];for(const lang of langs){if(lang==='cn'&&!e.has_cn)continue;try{const p=source(e,sec,lang),v=await json(RAW+enc(p),12*1024*1024);if(!v.story)throw Error('缺少 story');return{script:v,label:`${title(e)} · ${sec} · ${lang.toUpperCase()}`};}catch(x){errs.push(`${lang}: ${x.message}`);}}throw Error(errs.join('; '));}
function installCatalog(){if(id('full-story-catalog'))return;const panels=document.querySelectorAll('.global_quest_page .bg_change_img');if(panels.length<2)return;panels[0].innerHTML=`<img src="./image/image_web/common/frame/frame_title.png" class="frame_title full-title"><div class="bg_change_font">剧情目录</div><div id="full-story-catalog"><label>搜索<input id="full-story-search" type="search" placeholder="编号 / 标题"></label><label>分类<select id="full-story-category"><option value="">全部分类</option></select></label><label class="full-check"><input id="full-story-cn" type="checkbox" checked>优先中文</label><div class="full-pages"><button id="full-prev">上一页</button><span id="full-page">1 / 1</span><button id="full-next">下一页</button></div><div id="full-story-status">等待目录。</div></div>`;const list=panels[1].querySelector('.quest_list');list.id='full-story-list';list.replaceChildren();panels[1].querySelector('.bg_change_font').textContent='全剧情';id('full-story-search').oninput=()=>{S.page=0;render();};id('full-story-category').onchange=()=>{S.page=0;render();};id('full-prev').onclick=()=>{S.page=Math.max(0,S.page-1);render();};id('full-next').onclick=()=>{S.page++;render();};}
function render(){const root=id('full-story-list');if(!root)return;const q=norm(id('full-story-search')?.value),cat=id('full-story-category')?.value||'';S.shown=S.all.filter(e=>(!cat||e.category===cat)&&(!q||norm(`${e.id} ${e.title||''} ${e.folder}`).includes(q))).sort((a,b)=>coll.compare(title(a),title(b)));const pages=Math.max(1,Math.ceil(S.shown.length/S.size));S.page=Math.max(0,Math.min(S.page,pages-1));root.replaceChildren();S.shown.slice(S.page*S.size,(S.page+1)*S.size).forEach(e=>root.append(row(e)));id('full-page').textContent=`${S.page+1} / ${pages}`;id('full-prev').disabled=S.page===0;id('full-next').disabled=S.page>=pages-1;status(`匹配 ${S.shown.length.toLocaleString()} 部剧情`);}
function row(e){const w=document.createElement('div');w.className='quest_btn full-story';const h=document.createElement('button');h.className='quest_btn_2 full-story-head';h.innerHTML='<img class="quest_btn_2_img" src="./image/image_web/common/frame/title_icon.png"><span class="quest_btn_2_t"></span><img class="quest_btn_2_img2" src="./image/image_web/page/quest/btn_list_close.png">';h.querySelector('span').textContent=title(e);const sec=document.createElement('div');sec.className='full-sections';sec.hidden=true;h.onclick=()=>{S.selected=e;sec.hidden=!sec.hidden;w.classList.toggle('open',!sec.hidden);if(!sec.childElementCount)e.sections.forEach((x,i)=>sec.append(sectionButton(e,x,i)));};w.append(h,sec);return w;}
function sectionButton(e,sec,i){const b=document.createElement('button');b.className='full-section';b.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b><span></span><small>${e.has_cn?'CN/JP':'JP'}</small>`;b.querySelector('span').textContent=sec;b.onclick=async ev=>{ev.stopPropagation();b.disabled=true;status(`正在载入 ${e.id} / ${sec}…`);try{const v=await loadSection(e,sec);S.player.load(v.script,v.label);status(`已载入 ${v.label}`);}catch(x){status(`载入失败：${x.message}`,true);}finally{b.disabled=false;}};return b;}
function overlay(){if(id('full-story-overlay'))return;const n=document.createElement('div');n.id='full-story-overlay';n.innerHTML='<canvas id="full-fx"></canvas><div id="full-screen-fx"></div><div id="full-narration" hidden><strong id="full-narration-name"></strong><div id="full-narration-text"></div></div><div id="full-choices" hidden></div><div id="full-progress"></div><div id="full-log" hidden><header>LOG<button id="full-log-close">×</button></header><main id="full-log-body"></main></div>' ;document.querySelector('.story_page').append(n);}
class Player{
constructor(){this.groups={};this.order=[];this.group='';this.i=-1;this.names=['','',''];this.chars=new Map;this.slots=new Map;this.timer=0;this.typing=0;this.full='';this.node=null;this.auto=false;this.skip=false;this.playing=false;this.waiting=false;this.gen=0;this.bind();}
bind(){document.querySelector('.story_page').addEventListener('click',e=>{if(e.target.closest('#full-choices,#full-log,#story_log,#story_auto,#story_skip'))return;this.next();});$('#story_auto').off('click.full').on('click.full',e=>{e.stopPropagation();this.auto=!this.auto;if(this.auto)this.skip=false;this.buttons();});$('#story_skip').off('click').on('click.full',e=>{e.stopPropagation();this.skip=!this.skip;if(this.skip)this.auto=false;this.buttons();if(this.skip)this.schedule({},40);});$('#story_log').off('click.full').on('click.full',e=>{e.stopPropagation();id('full-log').hidden=!id('full-log').hidden;});id('full-log-close').onclick=e=>{e.stopPropagation();id('full-log').hidden=true;};}
buttons(){id('story_auto').classList.toggle('full-active',this.auto);id('story_skip').classList.toggle('full-active',this.skip);}
load(s,label){this.stop(false);this.groups=s.story;this.order=Object.keys(this.groups).filter(k=>Array.isArray(this.groups[k])).sort(coll.compare);this.group=this.order[0];this.i=-1;this.names=['','',''];this.playing=true;window.story_playing=true;$('.global_quest_page').hide();$('#back_main').hide();$('.story_page').show();$('#canvas').show();id('full-progress').textContent=label;id('full-log-body').replaceChildren();this.next();}
stop(back){this.gen++;this.playing=false;window.story_playing=false;clearTimeout(this.timer);clearInterval(this.typing);this.chars.forEach(r=>{try{app.stage.removeChild(r.sprite);r.sprite.destroy({children:true});}catch(e){}});this.chars.clear();this.slots.clear();this.hide();id('full-choices').hidden=true;id('full-narration').hidden=true;id('full-log').hidden=true;if(back)window.global_quest_page();}
complete(){if(!this.typing)return false;clearInterval(this.typing);this.typing=0;this.node.textContent=this.full;return true;}
async next(){if(!this.playing||this.waiting)return;if(this.complete())return;clearTimeout(this.timer);const a=this.groups[this.group]||[];if(++this.i>=a.length){this.playing=false;id('full-progress').textContent='END';return;}const s=a[this.i],g=++this.gen;try{if(s.bg!==undefined)this.bg(s.bg);await this.characters(s.chara||[],g);this.effect(s);this.dialogue(s);this.choices(s.select);id('full-progress').textContent=`${this.group} · ${this.i+1}/${a.length}`;this.schedule(s);}catch(e){console.warn(e);}}
bg(v){const n=id('story_bg');if(v==='black'){n.src='image/package/story/adv_black.jpg';return;}const raw=String(v),stem=raw.replace(/\.(jpg|png|webp)$/i,'');let a=[`image/image_native/bg/story/${raw}`,`image/image_native/bg/story/${stem}.jpg`,`${R2}/bg/story/${encodeURIComponent(stem)}.jpg`],i=0;n.onerror=()=>{if(i<a.length)n.src=a[i++];};n.onerror();}
async characters(a,g){for(const p of a){if(!p||p.id===undefined)continue;const key=String(p.id);if(String(p.effect||'').toLowerCase()==='fadeout'){this.remove(key);continue;}let r=this.chars.get(key);if(p.pos!==undefined||!r)r=await this.ensure(key,p.pos??r?.slot??1,g);if(!r||g!==this.gen)return;try{if(p.motion!==undefined)r.sprite.change_motion?.(p.motion);if(p.face)r.sprite.change_exp?.(p.face);if(p.cheek!==undefined)r.sprite.internalModel.coreModel.setParameterValueById('ParamCheek',+p.cheek);}catch(e){}if(p.effect)this.particles(p.effect,r.slot);}}
async ensure(key,slot,g){if(this.chars.has(key))this.remove(key);const old=this.slots.get(slot);if(old)this.remove(old);let base=`./image/image_native/live2d_v4/${key}/`;try{const r=await fetch(base+'model.model3.json',{method:'HEAD'});if(!r.ok)base=`${R2}/live2d_v4/${encodeURIComponent(key)}/`;}catch(e){base=`${R2}/live2d_v4/${encodeURIComponent(key)}/`;}const sprite=await window.show2(base,'model.model3.json',POS[slot]||POS[1]);if(g!==this.gen){sprite.destroy();return null;}const r={key,slot,sprite};this.chars.set(key,r);this.slots.set(slot,key);return r;}
remove(key){const r=this.chars.get(String(key));if(!r)return;this.chars.delete(String(key));if(this.slots.get(r.slot)===String(key))this.slots.delete(r.slot);try{app.stage.removeChild(r.sprite);r.sprite.destroy({children:true});}catch(e){}}
parse(x){return String(x||'').replace(/@/g,'\n').replace(/\[br\]/gi,'\n').replace(/\[(?:surround|se|jingle|bgm|flashEffect|chara|effect):[^\]]+\]/gi,'').replace(/\[text(?:Red|Blue|Yellow|Black):([\s\S]*?)\]/gi,'$1').trim();}
dialogue(s){if(s.nameLeft!==undefined)this.names[0]=s.nameLeft;if(s.nameCenter!==undefined)this.names[1]=s.nameCenter;if(s.nameRight!==undefined)this.names[2]=s.nameRight;const f=[['textLeft',0],['textCenter',1],['textRight',2],['textAvLeft',0],['textAvCenter',1],['textAvRight',2]].find(x=>s[x[0]]!==undefined);if(s.narration!==undefined||s.progressNarration!==undefined||s.progressFnarration!==undefined){this.hide();id('full-narration').hidden=false;id('full-narration-name').textContent=s.nameNarration||s.nameFnarration||'';this.type(id('full-narration-text'),this.parse(s.narration??s.progressNarration??s.progressFnarration));return;}id('full-narration').hidden=true;if(!f)return;const pos=f[1],sf=pos===0?'l':pos===2?'r':'c',text=this.parse(s[f[0]]);this.hide();id(`story_name_${sf}`).textContent=this.names[pos];id(`story_name_${sf}`).style.display='block';id(`story_log_ui_${sf}`).style.display='block';id(`story_context_${sf}`).style.display='block';this.type(id(`story_context_${sf}`),text);this.log(this.names[pos],text);const c=this.chars.get(this.slots.get(pos));c?.sprite.start_m?.();setTimeout(()=>c?.sprite.stop_m?.(),800);}
type(n,t){clearInterval(this.typing);this.node=n;this.full=t;n.textContent='';if(this.skip){n.textContent=t;return;}let i=0;this.typing=setInterval(()=>{n.textContent+=t[i++]||'';if(i>=t.length){clearInterval(this.typing);this.typing=0;}},25);}
hide(){['l','c','r'].forEach(s=>['story_name_','story_context_','story_log_ui_'].forEach(p=>{const n=id(p+s);if(n)n.style.display='none';}));}
choices(a){const n=id('full-choices');n.replaceChildren();if(!a?.length){n.hidden=true;this.waiting=false;return;}this.waiting=true;n.hidden=false;a.forEach(o=>{const b=document.createElement('button');b.textContent=this.parse(o.textSelect||o.group);b.onclick=e=>{e.stopPropagation();if(this.groups[o.group]){this.group=o.group;this.i=-1;this.waiting=false;n.hidden=true;this.next();}};n.append(b);});}
effect(s){if(s.flashEffect){const n=id('full-screen-fx');n.className=String(s.flashEffect).toLowerCase().includes('white')?'white active':'black active';setTimeout(()=>n.className='',450);}if(s.shake){const p=document.querySelector('.story_page');p.classList.remove('full-shake');void p.offsetWidth;p.classList.add('full-shake');}[s.textLeft,s.textCenter,s.textRight].filter(Boolean).forEach(t=>{let m,r=/\[chara:([^:\]]+):([^\]]+)\]/g;while((m=r.exec(t))){const c=this.chars.get(String(m[1]));this.particles(m[2],c?.slot??1);}});}
particles(v,slot){const n=document.createElement('div');n.className='full-emotion';n.textContent=String(v).includes('joy')?'♥':String(v).includes('question')?'?':String(v).includes('note')?'♪':'✦';n.style.left=(slot===0?25:slot===2?75:50)+'%';n.style.color=String(v).includes('sad')?'#78c9ff':'#ff75ad';id('full-story-overlay').append(n);setTimeout(()=>n.remove(),1100);}
log(a,b){const n=document.createElement('div');n.innerHTML='<strong></strong><p></p>';n.querySelector('strong').textContent=a||'';n.querySelector('p').textContent=b;id('full-log-body').append(n);}
schedule(s,force){clearTimeout(this.timer);if(!this.playing||this.waiting)return;if(!this.auto&&!this.skip&&s.autoTurnLast===undefined&&!force)return;const d=force||this.skip?55:s.autoTurnLast!==undefined?Math.max(120,+s.autoTurnLast*1000):Math.max(900,this.full.length*55+600),g=this.gen;this.timer=setTimeout(()=>{if(g===this.gen)this.next();},d);}
}
function install(){const css=document.createElement('link');css.rel='stylesheet';css.href='./css/full_story_catalog.css';document.head.append(css);overlay();S.player=new Player;S.oldQuest=window.global_quest_page;S.oldMain=window.main_page;window.global_quest_page=function(){if(S.player.playing)S.player.stop(false);S.oldQuest();installCatalog();loadIndex().catch(()=>{});};window.start_story=async function(e,sec){if(e&&sec){const x=await loadSection(e,sec);S.player.load(x.script,x.label);return;}if(S.selected)return window.start_story(S.selected,S.selected.sections[0]);const r=await fetch('image/scenario/json/adv/scenario_3/310011-1.json');S.player.load(await r.json(),'310011-1');};window.run_story=a=>S.player.load({story:{group_1:a}},'兼容剧情');window.main_page=function(){if(S.player.playing)S.player.stop(false);return S.oldMain.apply(this,arguments);};console.log('[FULL STORY] catalog ready',REV);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();